
module.exports.constants = {
    user: {
        STATUS_ACTIVE: 'active',
        STATUS_INACTIVE: 'inactive',
        STATUS_BLOCK: 'block',
        STATUS_DELETE: 'delete',
        DELETED_BY_USER: 'user',
        DELETED_BY_ADMIN: 'admin',
        EMAIL_VERIFIED: 'verified',
        EMAIL_NOTVERIFIED: 'notverified',
        SUBSCRIPTION_FREE: 'free',
        SUBSCRIPTION_PAID: 'paid',
        REFERRAL_UNABLE: 'unable',
        REFERRAL_CLAIMABLE: 'claimable',
        REFERRAL_CLAIMED: 'claimed',
        BLACKLIST_NO: 'no',
        BLACKLIST_YES: 'yes',
        SIGNUP_STATUS_COMPLETED: 'completed',
        SIGNUP_STATUS_NOTCOMPLETED: 'notcompleted'
    },
    subscription: {
        STATUS_ACTIVE: 'active',
        STATUS_INACTIVE: 'inactive',
        STATUS_DELETE: 'delete'
    },
    userinfo: {
        GENDER_MALE: 'male',
        GENDER_FEMALE: 'female',
        GENDER_MALE_FEMALE_COUPLE: 'male_female_couple',
        GENDER_GAY_COUPLE: 'gay_couple',
        GENDER_LESBIAN_COUPLE: 'lesbian_couple',
        THERAPEUTIC: 'therapeutic',
        SENSUAL: 'sensual',
        BODYTYPE_SLIM_PALETTE: 'slim_palette',
        BODYTYPE_AVERAGE: 'average',
        BODYTYPE_GYM_FIT: 'gym_fit',
        BODYTYPE_MUSCULAR: 'muscular',
        BODYTYPE_FEW_POUND_AVERAGE: 'few_pound_average',
        BODYTYPE_LARGE: 'large',
        DRINKING_FREQUENTLY: 'frequently',
        DRINKING_OCCASIONALLY_SOCIALLY: 'occasionally_socially',
        DRINKING_NEVER: 'never',
        DRINKING_STOPPED_DRINKING: 'stopped_drinking',
        SMOKING_OCCASIONALLY_SOCIALLY: 'occasionally_socially',
        SMOKING_FREQUENTLY: 'frequently',
        SMOKING_NEVER: 'never',
        SMOKING_STOPPED_SMOKING: 'stopped_smoking',
        MASSAGE_FREQUENCY_DAILY: 'daily',
        MASSAGE_FREQUENCY_EVERY_WEEK: 'every_week',
        MASSAGE_FREQUENCY_EVERY_MONTH: 'every_month',
        MASSAGE_FREQUENCY_EVERY_SIX_MONTH: 'every_six_months',
        MASSAGE_FREQUENCY_ONCE_A_YEAR: 'once_a_year',
        MASSAGE_FREQUENCY_NEVER: 'never',
        USER_LEVEL_PROFESSIONAL_CMT: 'professional_cmt',
        USER_LEVEL_STUDENT: 'student',
        USER_LEVEL_AFICIONADO: 'aficionado',
        EXPERIENCE_NONE: 'none_at_all',
        EXPERIENCE_0_TO_1: '0_1',
        EXPERIENCE_1_TO_2: '1_2',
        EXPERIENCE_2_TO_5: '2_5',
        EXPERIENCE_5_TO_10: '5_10',
        EXPERIENCE_10_TO_20: '10_20',
        EXPERIENCE_MORE_THAN_20: 'more_than_20_years',
        MASSAGE_STYLE_DEEP_TISSUE_STRONG: 'deep_tissue_strong',
        MASSAGE_STYLE_THAI: 'thai',
        MASSAGE_STYLE_REFLEXOLOGY: 'reflexology',
        MASSAGE_STYLE_SWEDISH: 'swedish',
        MASSAGE_STYLE_CHINESE: 'chinese',
        MASSAGE_STYLE_OTHERS: 'others',
        TRAINING_HOURS_FORMAL: 'no_formal_training',
        TRAINING_HOURS_UNDER_100: 'under_100hours',
        TRAINING_HOURS_101_TO_200: '101_200hours',
        TRAINING_HOURS_201_TO_300: '201_300hours',
        TRAINING_HOURS_301_TO_500: '301_500hours',
        TRAINING_HOURS_501_TO_1000: '501_1000hours',
        TRAINING_HOURS_MORE_THAN_1000: 'more_than_1000hours',
        
        SERVICE_RECEIVE_ONLY: 'receive_only',
        SERVICE_GIVE_ONLY: 'give_only',
        SERVICE_EXCHANGE: 'exchange',
        SERVICE_PAY_RIGHT_MASSEUR: 'pay_right_masseur',
        
        RELATIONSHIP_PARTNER: 'partner',
        RELATIONSHIP_FRIENDSHIP: 'friendship',
        RELATIONSHIP_INTIMATE: 'intimate',
        RELATIONSHIP_ROMANCE: 'romance',
        
        
        
        BODYTYPE_QUESTION_NOT_IMPORTANT: 'this_question_is_not_important',
        THERAPEUTIC_YES: 'yes',
        THERAPEUTIC_NO: 'no',
        SENSUAL_YES: 'yes',
        SENSUAL_NO: 'no',
    },
    video: {
        ACCESS_TYPE_PRIVATE: 'private',
        ACCESS_TYPE_PUBLIC: 'public',
        STATUS_ACTIVE: 'active',
        STATUS_INACTIVE: 'inactive',
        STATUS_DELETE: 'delete'
    },
    photo: {
        ACCESS_TYPE_PRIVATE: 'private',
        ACCESS_TYPE_PUBLIC: 'public',
        STATUS_ACTIVE: 'active',
        STATUS_INACTIVE: 'inactive',
        STATUS_DELETE: 'delete'
    },
    review: {
        REVIEW_STATUS_APPROVED: 'approved',
        REVIEW_STATUS_NOTAPPROVED: 'notapproved'
    },
    report: {
        REPORT_STATUS_APPROVED: 'approved',
        REPORT_STATUS_NOTAPPROVED: 'notapproved'
    },
    admin: {
        ADMIN_TYPE_SUPERADMIN: 'super_admin',
        ADMIN_TYPE_SUBADMIN: 'sub_admin',
        BLOCK_STATUS_BLOCK: 'block',
        BLOCK_STATUS_ACTIVE: 'active',
        BLOCK_STATUS_DELETE: 'delete',
    },
    conversation: {
        REQUEST_STATUS_ACCEPT: 'accept',
        REQUEST_STATUS_DECLINE: 'decline',
        REQUEST_STATUS_BLOCK: 'block',
    },
    mail: {
        SENDER_STATUS_SENT: 'sent',
        SENDER_STATUS_DRAFT: 'draft',
        SENDER_STATUS_TRASH: 'trash',
        SENDER_STATUS_FOLDER: 'folder',
        SENDER_STATUS_DELETE: 'delete',
        RECEIVER_STATUS_INBOX: 'inbox',
        RECEIVER_STATUS_TRASH: 'trash',
        RECEIVER_STATUS_FOLDER: 'folder',
        RECEIVER_STATUS_DELETE: 'delete',
        VIEW_STATUS_READ: 'read',
        VIEW_STATUS_UNREAD: 'unread',
    },
    blog: {
        AUTHOR_TYPE_SUPERADMIN: 'admin',
        AUTHOR_TYPE_SUBADMIN: 'sub_admin',
        AUTHOR_TYPE_USER: 'user',
        BLOG_STATUS_ACTIVE: 'active',
        BLOG_STATUS_INACTIVE: 'inactive',
        BLOG_STATUS_DELETE: 'delete',
        APPROVAL_STATUS_PENDING: 'pending',
        APPROVAL_STATUS_APPROVED: 'approved',
        APPROVAL_STATUS_REJECTED: 'rejected',
    },
    poll: {
        AUTHOR_TYPE_SUPERADMIN: 'admin',
        AUTHOR_TYPE_SUBADMIN: 'sub_admin',
        AUTHOR_TYPE_USER: 'user',
        POLL_STATUS_ACTIVE: 'active',
        POLL_STATUS_INACTIVE: 'inactive',
        POLL_STATUS_DELETE: 'delete',
        COMMENT_STATUS_SHOW: 'show',
        COMMENT_STATUS_HIDE: 'hide',
        APPROVAL_STATUS_PENDING: 'pending',
        APPROVAL_STATUS_APPROVED: 'approved',
        APPROVAL_STATUS_REJECTED: 'rejected',
        ANSWER_TYPE_RADIOBUTTON: 'radiobutton',
        ANSWER_TYPE_CHECKBOX: 'checkbox',
    },
    pollDetails: {
        APPROVAL_STATUS_APPROVED: 'approved',
        APPROVAL_STATUS_REJECTED: 'rejected',
    },
    adUser: {
        BANNER_TYPE_THERAPEUTIC: 'therapeutic',
        BANNER_TYPE_SENSUAL: 'sensual',
        ADUSER_STATUS_ACTIVE: 'active',
        ADUSER_STATUS_INACTIVE: 'inactive',
        ADUSER_STATUS_DELETE: 'delete',
    },
    userSettings: {
        SEARCH_PROFILE_STATUS_ENABLE: 'enable',
        SEARCH_PROFILE_STATUS_DISABLE: 'disable',
        SENSUAL_ADSTATUS_ENABLE: 'enable',
        SENSUAL_ADSTATUS_DISABLE: 'disable',
        AUTO_LOGIN_ENABLE: 'enable',
        AUTO_LOGIN_DISABLE: 'disable',
        SET_OFFLINE_ENABLE: 'enable',
        SET_OFFLINE_DISABLE: 'disable',
        FAVOURITE_MAIL_STATUS_ENABLE: 'enable',
        FAVOURITE_MAIL_STATUS_DISABLE: 'disable',
        PROVISIT_MAIL_STATUS_ENABLE: 'enable',
        PROVISIT_MAIL_STATUS_DISABLE: 'disable',
        NEW_MAIL_STATUS_ENABLE: 'enable',
        NEW_MAIL_STATUS_DISABLE: 'disable',
        POLL_MAIL_STATUS_ENABLE: 'enable',
        POLL_MAIL_STATUS_DISABLE: 'disable',
    },
    adPage: {
        STATUS_ACTIVE: 'active',
        STATUS_INACTIVE: 'inactive',
    },
    adPosition: {
        STATUS_ACTIVE: 'active',
        STATUS_INACTIVE: 'inactive',
    },
    cmsPage: {
        STATUS_ACTIVE: 'active',
        STATUS_INACTIVE: 'inactive',
    },
};
