
module.exports.constants = {
    user: {
        STATUS_ACTIVE: 'active',
        STATUS_INACTIVE: 'inactive',
        STATUS_BLOCK: 'block',
        STATUS_DELETE: 'delete',
        DELETED_BY_USER: 'user',
        DELETED_BY_ADMIN: 'admin',
        EMAIL_VERIFIED: 'verified',
        EMAIL_NOTVERIFIED: 'notverified',
        SUBSCRIPTION_FREE: 'free',
        SUBSCRIPTION_PAID: 'paid',
        REFERRAL_UNABLE: 'unable',
        REFERRAL_CLAIMABLE: 'claimable',
        REFERRAL_CLAIMED: 'claimed',
        BLACKLIST_NO: 'no',
        BLACKLIST_YES: 'yes'
    },
    subscription: {
        STATUS_ACTIVE: 'active',
        STATUS_INACTIVE: 'inactive',
        STATUS_DELETE: 'delete'
    },
    userinfo: {
        GENDER_MALE: 'male',
        GENDER_FEMALE: 'female',
        GENDER_MALE_FEMALE_COUPLE: 'male_female_couple',
        GENDER_GAY_COUPLE: 'gay_couple',
        GENDER_LESBIAN_COUPLE: 'lesbian_couple',
        USER_LEVEL_PROFESSIONAL_CMT: 'professional_body_worker_or_CMT',
        USER_LEVEL_STUDENT: 'massage_student',
        USER_LEVEL_AFICIONADO: 'aficionado',
        EXPERIENCE_NONE: 'none_at_all',
        EXPERIENCE_0_TO_1: '0-1',
        EXPERIENCE_1_TO_2: '1-2',
        EXPERIENCE_2_TO_5: '2-5',
        EXPERIENCE_5_TO_10: '5-10',
        EXPERIENCE_10_TO_20: '10-20',
        EXPERIENCE_MORE_THAN_20: 'more_than_20_years',
        BODYTYPE_MUSCULAR: 'muscular',
        BODYTYPE_GYMFIT: 'gymfit',
        BODYTYPE_AVERAGE: 'average',
        BODYTYPE_SLENDER: 'slender',
        BODYTYPE_EXTRA_POUNDS: 'few_extra_pounds',
        BODYTYPE_QUESTION_NOT_IMPORTANT: 'this_question_is_not_important',
        MASSAGE_FREQUENCY_DAILY: 'daily_or_almost_daily',
        MASSAGE_FREQUENCY_ONCE_A_WEEK: 'about_once_a_week',
        MASSAGE_FREQUENCY_EVERY_WEEK: 'every_few_weeks',
        MASSAGE_FREQUENCY_ONCE_A_MONTH: 'about_once_a_month',
        MASSAGE_FREQUENCY_EVERY_MONTH: 'every_few_months',
        MASSAGE_FREQUENCY_EVERY_SIX_MONTH: 'about_every_six_months',
        MASSAGE_FREQUENCY_ONCE_A_YEAR: 'about_once_a_year',
        DRINKING_GAVE_IT_UP: 'gave_it_up',
        DRINKING_SOCIALLY: 'socially',
        DRINKING_REGULARLY: 'regularly',
        DRINKING_NON_ALCOHOLIC: 'non_alcoholic_beverages_only',
        SMOKING_NEVER: 'never',
        SMOKING_EX_SMOKER: 'ex-smoker',
        SMOKING_OCCASIONALLY: 'occasionally',
        SMOKING_DAILY: 'daily',
        SMOKING_SOCIALLY: 'socially',
        SMOKING_TELL_YOU_LATER: 'i_will_tell_you_later',
        TRAINING_HOURS_FORMAL: 'no_formal_training',
        TRAINING_HOURS_UNDER_100: 'under_100hours',
        TRAINING_HOURS_101_TO_200: '101-200hours',
        TRAINING_HOURS_201_TO_300: '201-300hours',
        TRAINING_HOURS_301_TO_500: '301-500hours',
        TRAINING_HOURS_501_TO_1000: '501-1000hours',
        TRAINING_HOURS_MORE_THAN_1000: 'more_than_1000hours',
        THERAPEUTIC_YES: 'yes',
        THERAPEUTIC_NO: 'no',
        SENSUAL_YES: 'yes',
        SENSUAL_NO: 'no',
    },
    video: {
        ACCESS_TYPE_PRIVATE: 'private',
        ACCESS_TYPE_PUBLIC: 'public'
    },
    photo: {
        ACCESS_TYPE_PRIVATE: 'private',
        ACCESS_TYPE_PUBLIC: 'public'
    }
};
