--
-- Table structure for table `userinfo`
--

CREATE TABLE IF NOT EXISTS `userinfo` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `userId` int(11) NOT NULL,
  `gender` enum('male','female','male_female_couple','gay_couple','lesbian_couple') DEFAULT NULL,
  `telephone` varchar(15) DEFAULT NULL,
  `zipcode` varchar(10) DEFAULT NULL,
  `country` varchar(50) DEFAULT NULL,
  `state` varchar(50) DEFAULT NULL,
  `city` varchar(50) DEFAULT NULL,
  `latitude` varchar(30) DEFAULT NULL,
  `longitude` varchar(30) DEFAULT NULL,
  `therapeuticMassageOne` enum('therapeutic') DEFAULT NULL,
  `therapeuticMassageOneDesc` text,
  `sensualMassageOne` enum('sensual') DEFAULT NULL,
  `sensualMassageOneDesc` text,
  `dobOne` date DEFAULT NULL,
  `ageOne` int(3) DEFAULT NULL,
  `languageOne` varchar(50) DEFAULT NULL,
  `bodyTypeOne` enum('slim_palette','average','gym_fit','muscular','few_pound_average','large') DEFAULT NULL,
  `heightOne` int(4) DEFAULT NULL,
  `drinkingHabitOne` enum('occasionally_socially','frequently','never','stopped_drinking') DEFAULT NULL,
  `smokingHabitOne` enum('occasionally_socially','frequently','never','stopped_smoking') DEFAULT NULL,
  `massageFrequencyOne` enum('daily','every_week','every_month','every_six_months','once_a_year','never') DEFAULT NULL,
  `levelTypeOne` enum('professional_cmt','student','aficionado') DEFAULT NULL,
  `levelTypeOneOther` varchar(150) DEFAULT NULL,
  `experienceOne` enum('none_at_all','0_1','1_2','2_5','5_10','10_20','more_than_20_years') DEFAULT NULL,
  `massageStylesOne` enum('deep_tissue_strong','thai','reflexology','swedish','chinese','others') DEFAULT NULL,
  `massageStylesOneOther` varchar(150) DEFAULT NULL,
  `trainingHoursOne` enum('no_formal_training','under_100hours','101_200hours','201_300hours','301_500hours','501_1000hours','more_than_1000hours') DEFAULT NULL,
  `therapeuticMassageTwo` enum('therapeutic') DEFAULT NULL,
  `therapeuticMassageTwoDesc` text,
  `sensualMassageTwo` enum('sensual') DEFAULT NULL,
  `sensualMassageTwoDesc` text,
  `dobTwo` date DEFAULT NULL,
  `ageTwo` int(3) DEFAULT NULL,
  `languageTwo` varchar(50) DEFAULT NULL,
  `bodyTypeTwo` enum('slim_palette','average','gym_fit','muscular','few_pound_average','large') DEFAULT NULL,
  `heightTwo` int(4) DEFAULT NULL,
  `drinkingHabitTwo` enum('occasionally_socially','frequently','never','stopped_drinking') DEFAULT NULL,
  `smokingHabitTwo` enum('occasionally_socially','frequently','never','stopped_smoking') DEFAULT NULL,
  `massageFrequencyTwo` enum('daily','every_week','every_month','every_six_months','once_a_year','never') DEFAULT NULL,
  `levelTypeTwo` enum('professional_cmt','student','aficionado') DEFAULT NULL,
  `levelTypeTwoOther` varchar(150) DEFAULT NULL,
  `experienceTwo` enum('none_at_all','0_1','1_2','2_5','5_10','10_20','more_than_20_years') DEFAULT NULL,
  `massageStylesTwo` enum('deep_tissue_strong','thai','reflexology','swedish','chinese','others') DEFAULT NULL,
  `massageStylesTwoOther` varchar(150) DEFAULT NULL,
  `trainingHoursTwo` enum('no_formal_training','under_100hours','101_200hours','201_300hours','301_500hours','501_1000hours','more_than_1000hours') DEFAULT NULL,
  `lastLoggedin` datetime DEFAULT NULL,
  `createdAt` datetime DEFAULT NULL,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

